[package]
name = "wavyte"
version = "0.1.0"
edition = "2024"

[features]
default = []
gpu = []
cpu = []
hybrid = []
cli = []
napi = []

[dependencies]
anyhow = "1"
kurbo = { version = "0.13", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tracing = { version = "0.1", features = ["attributes"] }

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["fmt"] }

